### ISSUE TITLE
Jinja templating seems to be crashing PyStack with an `IndexError`

### ISSUE THREAD

**Issue by strugee** [bloomberg/pystack#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
<irrelevant stack trace output truncated>
    (Python) File "/opt/venvs/debtsy/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
        rv = template.render(context)
    (Python) File "/opt/venvs/debtsy/lib/python3.9/site-packages/ddtrace/contrib/jinja2/patch.py", line 70, in _wrap_render
        return wrapped(*args, **kwargs)
    (Python) File "/opt/venvs/debtsy/lib/python3.9/site-packages/jinja2/environment.py", line 1043, in render
        return concat(self.root_render_func(self.new_context(vars)))
    (Python) File "/opt/venvs/debtsy/lib/python3.9/site-packages/flask_admin/templates/bootstrap3/admin/model/edit.html", line 24, in root
        {%- if admin_view.can_view_details -%}
    (Python) File "/opt/venvs/debtsy/lib/python3.9/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 16, in root
Traceback (most recent call last):
  File "/root/venv/bin/pystack", line 8, in <module>
    sys.exit(main())
  File "/root/venv/lib/python3.8/site-packages/pystack/__main__.py", line 254, in main
    args.func(parser, args)
  File "/root/venv/lib/python3.8/site-packages/pystack/__main__.py", line 381, in process_core
    print_thread(thread, native)
  File "/root/venv/lib/python3.8/site-packages/pystack/traceback_formatter.py", line 15, in print_thread
    for line in format_thread(thread, native):
  File "/root/venv/lib/python3.8/site-packages/pystack/traceback_formatter.py", line 81, in format_thread
    yield from format_frame(current_frame)
  File "/root/venv/lib/python3.8/site-packages/pystack/traceback_formatter.py", line 29, in format_frame
    source = lines[code.location.lineno - 1]
IndexError: list index out of range
```

### Expected Behavior

PyStack does not crash when processing this process.

### Steps To Reproduce

I can try and nail down a more constrained STR, but I'm not really sure what to actually try since that it's hard to reduce our entire app to a minimal example... given the traceback (see below), I figured I would file a bug and see if anyone had any ideas on what to try based on their knowledge of the way PyStack works.

PyStack was freshly installed from Pip FWIW, into a fresh virtual environment. This crash happened on both a coredump file and on a live process (processing a request for the same URL). We're running Ubuntu 20.04.6.

### Pystack Version

1.3.0

### Python Version

3.8

### Linux distribution

Ubuntu

**Comment by pablogsal** [comment]
Hi @strugee and thanks for the report! We can try to investigate but without a reproducer is very hard for us to do anything here. Can you try to get a small jinja-based example to see if it crashes?

if not, can you modify `/root/venv/lib/python3.8/site-packages/pystack/traceback_formatter.py` to print `lines` and `code.location`? Like so:

`
print(lines, code.location)
source = lines[code.location.lineno - 1]
`

**Comment by normamupa-a11y** [comment]
[](url

[AndroidManifest.xml](https://github.com/user-attachments/files/22975107/AndroidManifest.xml)

)

**Comment by pradyunsg** [comment]
https://github.com/bloomberg/pystack/compare/main...pradyunsg:pystack:191-repro?expand=1 has a reproducer created with Claude Code, while we were discussing this in the lobby at PyCon US.


```
~/Developer/github/pystack/repro/issue-191
❯ docker run --rm --cap-add=SYS_PTRACE --security-opt seccomp=unconfined pystack-191
PID=7

=== template before truncation ===
<html>
<body>
<ul>
{% for item in items %}<li>{{ item }}</li>
{% endfor %}
</ul>
</body></html>
=== /end ===

=== template after truncation (empty) ===
=== /end ===

>>> pystack remote 7
Traceback for thread 7 (python) [] (most recent call last):
    (Python) File "/app/blocker.py", line 18, in <module>
        sys.stdout.write(template.render(items=slow_items()))
    (Python) File "/usr/local/lib/python3.14/site-packages/jinja2/environment.py", line 1293, in render
        return self.environment.concat(self.root_render_func(ctx))  # type: ignore
    (Python) File "/app/templates/blocker.html", line 13, in root
Traceback (most recent call last):
  File "/usr/local/bin/pystack", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.14/site-packages/pystack/__main__.py", line 278, in main
    args.func(parser, args)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pystack/__main__.py", line 295, in process_remote
    print_thread(thread, args.native_mode)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pystack/traceback_formatter.py", line 16, in print_thread
    for line in format_thread(thread, native_mode):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pystack/traceback_formatter.py", line 84, in format_thread
    yield from format_frame(current_frame)
  File "/usr/local/lib/python3.14/site-packages/pystack/traceback_formatter.py", line 30, in format_frame
    source = lines[code.location.lineno - 1]
             ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
>>> pystack exit code: 1
```

**Comment by sarahmonod** [comment]
@kiri11 is working on this, but somehow I can only assign it to people who have commented on this issue. I'll assign it to me so that it doesn't appear in the list of unassigned issues.

**Comment by strugee** [comment]
Yay, exciting! This is giving me even more FOMO for sprints 😂
